--liquibase formatted sql

-- changeset rus.glee:1
create table sock
(
    id         integer generated by default as identity primary key,
    colour  varchar,
    cottonPart  varchar,
    quantity integer
);


